version: "3.7"
services:
  app:
    build: .
    volumes:
      - .:/usr/code
      - /usr/code/node_modules/
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST=magic.localhost
    command: yarn run dev
