version: "3.7"
services:
  postgres:
    image: postgres:11
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    depends_on:
      - postgres
    build: .
    volumes:
      - .:/usr/code
      - /usr/code/node_modules/
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"
    environment:
      VIRTUAL_HOST: magic.localhost
      PORT: ${PORT}
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    command: yarn run dev
