version: '3.7'
services:
  database:
    image: 'postgres:11'
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    depends_on:
      - database
    build: .
    volumes:
      - .:/usr/code
      - /usr/code/node_modules/
    ports:
      - ${APP_PORT}:3000
    environment:
      APP_PORT: ${APP_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    command: yarn run dev
volumes:
  data:
