version: '3.7'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  app:
    depends_on:
      - mongo
    build: .
    volumes:
      - .:/usr/code
      - /usr/code/node_modules/
    ports:
      - ${APP_PORT}:3000
    links:
      - mongo
    environment:
      APP_PORT: ${APP_PORT}
    command: yarn run dev
